[build]
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[identity]
  confirm = "https://stevegiancopy.com/admin/"
  invite = "https://stevegiancopy.com/admin/"
  recovery = "https://stevegiancopy.com/admin/"
